language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
 # - hexo g
  - hexo clean
  - hexo generate --deploy

after_script:
  - cd ./public
  - git init
  - git config user.name "Warpeas" --{GitHub账户名称}
  - git config user.email "M4A1go@163.com" --{Github账户邮箱}
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/Warpeas/warpeas.github.io.git