sudo: false
language: node_js
node_js: stable

# S: Build Lifecycle
# install:
#   - npm install

# #before_script:
#  # - npm install -g gulp

# script:
#  # - hexo g
#   - hexo clean
#   - hexo g -d

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "Warpeas" --{GitHub账户名称}
#   - git config user.email "M4A1go@163.com" --{Github账户邮箱}
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

cache: npm
branches:
  only:
    - master
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
env:
 global:
   - GH_REF: github.com/Warpeas/warpeas.github.io.git
